name: Deploy Website
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: echo 'Linting code'
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: echo 'Running unit tests'
  e2e_test:
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: echo 'Running end-to-end tests'
  
  build:
    runs-on: ubuntu-latest
    needs: [lint, unit_test, e2e_test]
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build