name: Deploy Website
on: 
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Lint code
        run: echo 'Linting code'
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Run tests
        run: echo 'Running unit tests'
  e2e_test:
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Run tests
        run: echo 'Running end-to-end tests'
  
  build:
    runs-on: ubuntu-latest
    needs: [lint, unit_test, e2e_test]
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
      - name: Install dependencies
        run: npm install pnpm -g && pnpm install
      - name: Build Project
        run: npm run build
      - name: save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Output files
        run: ls -R
      - name: Deploy to server
        run: echo 'Deploying to server'